FRAMEWORK_OPENSSL = "OpenSSL"
FRAMEWORK_CRYPTOGRAPHY = "Cryptography"
FRAMEWORK_LAB_EDUCATIONAL = "Lab Educational"
FRAMEWORK_CUSTOM_EDUCATIONAL = "Custom Educational"
FRAMEWORK_CUSTOM_LEGACY = "Custom Educational / Legacy"
FRAMEWORK_CUSTOM_ALIASES = {
    FRAMEWORK_CUSTOM_EDUCATIONAL,
    FRAMEWORK_CUSTOM_LEGACY,
}

ALGORITHM_AES_256_CBC = "AES-256-CBC"
ALGORITHM_AES_256_GCM = "AES-256-GCM"
ALGORITHM_DES_CBC = "DES-CBC"
ALGORITHM_RSA_2048 = "RSA-2048"
ALGORITHM_DES_LAB = "DES-LAB"
ALGORITHM_RSA_LAB = "RSA-LAB"
ALGORITHM_HYBRID_RSA_AES = "Hybrid RSA-AES"

OPERATION_ENCRYPT = "encrypt"
OPERATION_DECRYPT = "decrypt"

STATUS_PLAIN = "plain"
STATUS_RUNNING = "running"
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"
STATUS_ENCRYPTED = "encrypted"
STATUS_DECRYPTED = "decrypted"
